version: 0.0 #CodeDeploy 버전, 0.0이 아니면 오류 발생
os: linux
files:
  - source: / # S3경로
    destination: /home/ec2-user/app/step3/zip/ # EC2경로
    overwrite: yes

permissions: # CodeDeploy에서 EC2로 넘겨준 파일들을 모두 ec2-user권한을 갖도록 한다.
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks: # CodeDeploy 배포 단계에서 실행할 명령어를 지정
  AfterInstall:
    - location: stop.sh
      timeout: 60 # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스플이 부트를 시작
      timeout: 60 # 100초 이상 수행되면 실패
      runas: ec2-user